kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cilium-cluster
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 9100
    hostPort: 9100
- role: worker
- role: worker
- role: worker
